### ISSUE TITLE
[Empresa / Criar vaga] - Alterações no layout

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#135]
US Referente: https://github.com/SouJunior/products/issues/3

## SubTasks

- [ ] Alterar e implementar novas features do prótotipo.
- [ ] Cidade e UF não serão obrigátorias se a modalidade for Remoto.
- [ ] Grupo minoritário deve ser possivel selecionar mais de uma opção.
- [ ] Implementar TipTap ToolKit na descrição
