### ISSUE TITLE
[Candidato / Feed de vagas] - Lista de vagas

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#137]
US Referente: https://github.com/SouJunior/products/issues/37

## SubTasks

- [x] Estilizar card de vagas
- [x] Listar vagas na vertical
- [x] Implementar lazy loading

**Comment by JoaoKremerDev** [comment]
1. A primeira subtask [Estilizar card de vagas] ja está pronto e funcionando da forma que foi pedido. Ao clicar no card do candidato a cor fica com borda azul e as demais vagas que não foram selecionadas ficam com uma cor com um pouco mais de opacidade e ganham uma box-shadow bem leve.

**Comment by JoaoKremerDev** [comment]
Prezada equipe,

Tenho o prazer de informar que concluí a tarefa de estilizar as listas de cartões de vaga na página de feed. De acordo com as especificações de design fornecidas no protótipo do Figma, adicionei os estilos necessários aos cartões de vagas;

Além disso, implementei a funcionalidade de seleção de cartão, onde uma borda azul é adicionada ao cartão selecionado pelo usuário, e adicionei uma leve sombra e opacidade aos cartões não selecionados para destacar o selecionado. Também implementei a rolagem para visualizar as vagas que não estão completamente visíveis no container devido à altura.

Gostaria de ressaltar que adicionei uma barra de rolagem para indicar ao usuário que há a possibilidade de rolar a lista de empregos. No entanto, reconheço que no protótipo do Figma não constava essa opção. Estarei conversando com o designer responsável sobre o assunto e oferecendo minha sugestão. No entanto, seguiremos a escolha do nosso designer.

Além disso, criei a funcionalidade de "ver mais", que permite carregar 10 vagas de emprego adicionais a cada clique no botão correspondente. O botão "ver mais" muda para "carregando..." enquanto os dados são carregados da API. Também adicionei a funcionalidade de exibir a mensagem "Todas as vagas já foram exibidas" quando não houver mais vagas disponíveis no banco de dados, e desativar o botão para evitar que o usuário faça novas solicitações desnecessárias e sobrecarregue o back-end.

Para diminuir o peso no back-end, retirei a solicitação de vagas de emprego sempre que um cartão fosse selecionado, e armazenei a primeira solicitação em um estado para que pudéssemos trabalhar com os dados sem precisar fazer novas solicitações.

Agradeço a oportunidade de contribuir para o projeto e estou à disposição para qualquer esclarecimento adicional.

Atenciosamente,
João Vitor Melo Kremer.

**Comment by FernandoMiguelS** [comment]
Bom dia, sou o novo QA da Squad Cereal-Killers, fiz os testes e encontrei alguns pontos, a serem verificados. 

1 - Estilizar card de vagas - Ok
2 -  Listar vagas na vertical - Ok 
3 - Implementar carregamento lento




1 - Box-shadow nas vagas que não foram selecionadas, não existe no protótipo. - Validar com UX. 
2 - Funcionalidade "Todas as vagas já foram exibidas." não existe no protótipo. - Validar com UX.
3 - "Barra de rolagem" não existe no protótipo do Figma. Validar com o UX.




![Image](https://github.com/SouJunior/vagas-frontend/assets/134456312/91e451cd-a9e4-4e4e-bd08-e2723eeace9f)



Não entendi a task de implementar carregamento lento. Poderia me explicar? 



[\[Candidato  Feed de vagas\] Lista de vagas 137.docx](https://github.com/SouJunior/vagas-frontend/files/12139136/Candidato.Feed.de.vagas.Lista.de.vagas.137.docx)


Fiz este doc com as evidencias para melhor entendimento

**Comment by caiquefonseca** [comment]
@thiagosansi , imagino que você esteja por dentro dessas diferenças entre o protótipo e o desenvolvido. Daria para ajudar o @FernandoMiguelS a entender o que houve?

**Comment by thiagosansi** [comment]
@isabell40liveira por favor, atualiza o figma com os itens apontados. @FernandoMiguelS os itens apontados estão nos critérios de aceite da US.
