### ISSUE TITLE
[Candidato / Feed de vagas] - Campo de pesquisar vagas

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#138]
US Referente: https://github.com/SouJunior/products/issues/37

## SubTasks

- [x] Campo para buscar por nome.
- [x] Campo para buscar por remoto, cidade, estado ou país.
- [x] Botão para executar a pesquisa.
- [x] Exibir vagas filtradas.

**Comment by FernandoMiguelS** [comment]
1 - Campo para buscar por nome. Ok
2 - Campo para buscar por remoto, cidade, estado ou país.  Ok
3 - Botão para executar a pesquisa. Ok
4 -Exibir vagas filtradas. Ok



![Image](https://github.com/SouJunior/vagas-frontend/assets/134456312/09ffc25b-9641-43d1-852c-b98345417e65)


Protótipo



![Image](https://github.com/SouJunior/vagas-frontend/assets/134456312/cc005f23-8556-40f2-ae96-a06dd7020491)

**Comment by caiquefonseca** [comment]
@FernandoMiguelS , se todos os itens da Task já estão testados, pode fechar o item.

**Comment by FernandoMiguelS** [comment]
Não estão validados, tinha validado apenas a existência desses campos, erro meu, realizei mais alguns testes e identifiquei que os campos de busca não estão funcionando. 

O campo "Cargo, empresa, palavra-chave" ao inserirmos algum cargo, não filtra, mesmo que o cargo já exista, ele mostra que não existem resultados, como mostra no vídeo
O campo "Local" , ao inserirmos um local, deixa o botão "Buscar Vagas" desabilitado. O botão para de funcionar.


https://drive.google.com/file/d/1zJD-XvZjkhB8w2TvMn9OS_-tWXBdCt3M/view?usp=sharing

**Comment by FernandoMiguelS** [comment]
Como alinhado com o Squad, os pontos abordados estão sendo tratados em outra task, então essa Task está validada.

**Comment by thiagosansi** [comment]
@FernandoMiguelS por favor, registra aqui nos comentários a task que foi referenciada para tratar os bugs encontrados.
