### ISSUE TITLE
[Candidato / Feed de vagas] - Área do usuário

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#141]
US Referente: https://github.com/SouJunior/products/issues/37

## SubTasks

- [x] Exibir imagem de perfil do usuário.
- [x] Link "Editar perfil" para encaminhar o usuário para tela de perfil.
- [x] Criar componente de status da vaga inscrita.
- [x] Seção exibindo Status das vagas inscritas.
