### ISSUE TITLE
[Home 3/3] - Áreas de atuação

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#166]
### US relacionada
https://github.com/SouJunior/products/issues/127

### Descrição
Nesta task, será criada a seção "Encontre sua Área de Atuação" na página inicial do portal SouJunior. Será necessário criar um título para essa seção, assim como um carrossel que irá exibir as áreas de atuação disponíveis. Quando o usuário clicar em alguma das áreas, será aberto um modal com informações específicas sobre a área selecionada. Será importante garantir que a usabilidade e a experiência do usuário sejam consideradas durante o desenvolvimento dessas funcionalidades.

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/237083979-c1b82de5-5744-4ccb-abc2-649f8f1cc5ef.png)

### Subtasks

- [x] Criar um h2 com a frase "Ainda não sabe para onde ir? Encontre-se aqui!".
- [x] Criar um carrossel para exibir as áreas de atuação.
- [x] Criar navegação do carrossel com drag e setinhas. 
- [x] Criar modal para exibir as informações da área de atuação.
