### ISSUE TITLE
[Home 3/3] - Depoimentos de juninhos

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#168]
### US relacionada
https://github.com/SouJunior/products/issues/127

### Descrição
Esta task consiste em criar uma seção no site com depoimentos de juninhos que foram beneficiados pelo ecossistema SouJunior. Para isso, é necessário selecionar alguns depoimentos relevantes e criar um carrossel com esses depoimentos, com animações suaves entre eles. Também é necessário adicionar indicadores visuais para mostrar em que posição o usuário está no carrossel, garantindo que a experiência do usuário seja clara e intuitiva.

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/237088491-df3c4696-4ca1-4ae8-be46-5990d087eff1.png)

### Subtasks

- [x] Selecionar depoimentos de juninhos que foram beneficiados pelo ecossistema SouJunior.
- [x] Criar carrossel com os depoimentos selecionados, com animações suaves.
- [x] Adicionar indicadores visuais para mostrar em que posição o usuário está no carrossel;
