### ISSUE TITLE
[Home 3/3] - Banner aplicativo SouJunior

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#169]
### US relacionada
https://github.com/SouJunior/products/issues/127

### Descrição
Essa task tem como objetivo a criação de um banner para indicação de download do aplicativo SouJunior na Play Store. 

### Protótipo
[Em desenvolvimento]

### Subtasks

- [ ] Criar banner com a indicação para baixar o aplicativo SouJunior na Play Store.
- [ ] Configurar o link para direcionar o usuário para a área de download do aplicativo na Play Store (se estiver acessando pelo windows ou android)
- [ ] Configurar o pop-up indicando que o aplicativo está disponível apenas para dispositivos Android (se estiver acessando por dispositivos IOS)
