### ISSUE TITLE
[Home - V1] - Main section

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#175]
### US relacionada
https://github.com/SouJunior/products/issues/224

### Descrição
Esta task tem como objetivo fazer alterações na parte principal e inicial da home, colocando o filtro de busca no header e alterando os estilos.

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/240241881-a0042a10-2a07-4af3-ada9-433f026f5fcc.png)

### Subtasks

- [x] Alterar estilos do filtro de busca;
- [x] Posicionar o filtro de busca no header;
- [x] Mudar os estilos do background;
- [x] Números de vagas sendo o menor número múltiplo de 10.
