### ISSUE TITLE
[Home - V1] - Header Features

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#178]
### US relacionada
https://github.com/SouJunior/products/issues/224

### Descrição
Esta task tem como objetivo fazer alterações no Header da home, caso o usuário esteja logado deverá aparecer a foto de perfil com algumas opções, caso ainda não esteja logado, deverá aparecer os botões de registre-se e cadastre-se.

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/240241881-a0042a10-2a07-4af3-ada9-433f026f5fcc.png)

### Subtasks

- [ ] Verificar se está logado;
- [ ] Condicional na foto de perfil ou botões;
- [ ] Componente com foto de perfil e opções.
