### ISSUE TITLE
[Candidato / Candidatura] - Filtro de busca

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#197]
US Relacionada - [#205]

### Descrição:
Essa task tem o objetivo de implementar a funcionalidade de filtrar vagas por meio de um campo de pesquisa e um select com opções de filtragem rápida. O objetivo é permitir que os usuários encontrem vagas específicas com facilidade, melhorando a usabilidade do aplicativo.

___

### Subtasks

- [ ] Implementar a lógica para enviar solicitações à API e recuperar os resultados filtrados com base nas palavras-chave inseridas.
- [ ] Integrar o select com a lógica de filtragem e enviar solicitações à API para recuperar os resultados filtrados com base na seleção do usuário.
- [ ] Atualizar dinamicamente os resultados exibidos na interface do aplicativo conforme as seleções do usuário ou a entrada de palavras-chave.

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/247092152-a283eef9-b2de-4c04-8ed7-7e2899f9f4e3.png)

![Image](https://user-images.githubusercontent.com/100960828/247092193-a1b269cd-9068-4203-bcee-00d08036c6fa.png)

___

### Critérios de Aceitação

- [ ] O campo de pesquisa permite que os usuários insiram palavras-chave para buscar vagas específicas;
- [ ] Deve ser possivel filtrar vagas pelo select;
- [ ] Os resultados das vagas são atualizados corretamente com base nas palavras-chave inseridas;
- [ ] Os resultados das vagas são atualizados corretamente com base na opção selecionada no select;
- [ ] A implementação segue as diretrizes de design e padrões definidos.

**Comment by caiquefonseca** [comment]
@limaricardo , dá uma olhada nessa belezura de Task. O @FilipeLeoni deixou tudo explicadinho!

**Comment by limaricardo** [comment]
> @limaricardo , dá uma olhada nessa belezura de Task. O @FilipeLeoni deixou tudo explicadinho!

@caiquefonseca coisa linda, tudo organizado e detalhado!

**Comment by jhonatancostaamaral** [comment]
Pessoal, do @SouJunior/frontend / @SouJunior/backend, quem está assumindo essa task, já que o @FilipeLeoni está ausente?

**Comment by caiquefonseca** [comment]
@limaricardo, você poderia nos ajudar na revisão desta task? A liberação dela vai ajudar em outro item, que atualmente está bloqueado em testes.

**Comment by mooncoded** [comment]
@FernandoMiguelS Isso se deve a um comportamento do backend, onde na rota para realizar a busca por filtro é obrigatório informar uma palavra chave para fazer a busca, sendo assim, não é possivel realizar a busca somente por Local, portanto, é necessario informar uma palavra chave em *conjunto* um Local, dessa forma, o filtro de local funcionara corretamente como evidenciado no video a seguir:

[](https://jam.dev/c/27dbf3e0-c9ee-41d5-a7fc-dc847ec494c7)

Vou buscar saber se esse comportamento era pra ser dessa forma ou foi algo que passou despercebido, ou eu que entendi algo errado.
