### ISSUE TITLE
[Candidato / Candidatura] - Receber e exibir curriculo

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#198]
US Relacionada - https://github.com/SouJunior/products/issues/205

### Descrição:
Essa task consiste em implementar a funcionalidade que permite receber e exibir o currículo do usuário logado. Caso o usuário não tenha currículo cadastrado, deve ser exibida a opção para anexar um currículo (porém, essa funcionalidade de anexar não será implementada por agora). Após receber os currículos, o usuário poderá selecionar um deles para visualização, ao clicar no currículo desejado, um arquivo PDF será exibido para que o usuário possa visualizá-lo.

___

### Subtasks

- [ ] Fazer requisição à API com o ID do usuário logado para receber os currículos associados.
- [ ] Implementar a exibição dos currículos recebidos em uma lista para que o usuário possa selecionar um deles.
- [ ] Ao selecionar um currículo, exibir o arquivo PDF correspondente para visualização.

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/247095379-38f9ca78-09a2-4cec-8b88-dc34f53abd81.png)

![Image](https://user-images.githubusercontent.com/100960828/247095421-f2160877-c3e3-4ce4-9049-32fcfc3f3a60.png)

___

### Critérios de aceitação:

- [ ] Os currículos associados ao usuário são recebidos corretamente através da API.
- [ ] Caso o usuário não tenha currículo cadastrado, é exibida a opção para anexar um currículo (essa funcionalidade não será implementada nessa task).
- [ ] Os currículos recebidos são exibidos lado a lado para que o usuário possa selecionar um deles.
- [ ] Ao selecionar um currículo, o arquivo PDF correspondente é exibido para que o usuário possa visualizá-lo corretamente.
- [ ] A funcionalidade é testada em diferentes cenários, garantindo que os currículos são recebidos e exibidos corretamente para usuários com e sem currículos cadastrados.
- [ ] A implementação segue as diretrizes de design e padrões definidos para o aplicativo.

**Comment by FilipeLeoni** [comment]
@caiquefonseca Está tudo finalizado, acabei esquecendo de atualizar!

**Comment by AlineBoechat** [comment]
@barbaraluzz essa US segue sendo válida? Pergunto para entender como seria o currículo e como poderíamos colocar essa visualização por parte da empresa.
