### ISSUE TITLE
[Candidato / Candidatura] - Exibir dados da empresa

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#199]
US Relacionada - https://github.com/SouJunior/products/issues/205

### Descrição:
Essa task tem como objetivo permitir a exibição das informações da empresa responsável pela vaga. Cada vaga contém o ID da empresa associada, e com base nesse ID, uma requisição à API deve ser feita para obter os dados da empresa e exibi-los nas vagas.
___

### Subtasks

- [ ] Extrair o ID da empresa da vaga atual.
- [ ] Fazer uma requisição à API utilizando o ID da empresa para obter os dados correspondentes.
- [ ] Exibir na página da vaga as informações da empresa, como foto e nome da empresa.

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/247097239-fc6dee24-2abc-4fb6-8463-4271410d45df.png)

![Image](https://user-images.githubusercontent.com/100960828/247097277-3a1e3e84-048c-4b0c-9070-e2333bb81517.png)

___

### Critérios de aceitação

- [ ] Uma requisição à API utilizando o ID da empresa é feita com sucesso.
- [ ] Os dados da empresa são recebidos corretamente através da API.
- [ ] As informações da empresa, como foto e nome, são exibidas na página da vaga.
- [ ] A funcionalidade é testada em diferentes cenários, garantindo que as informações da empresa sejam exibidas corretamente para cada vaga.
- [ ] A implementação segue as diretrizes de design e padrões definidos para o aplicativo.

**Comment by caiquefonseca** [comment]
@limaricardo ou @AdsonAmorim podem confirmar se esse item já foi aprovado? Caso sim, já pode ser movido para a próxima coluna.

**Comment by FernandoMiguelS** [comment]
Tentei realizar a criação de uma nova vaga para poder iniciar os testes dessa task, que visa exibir as informações da empresa responsável pela vaga. Mas está exibindo a mensagem de erro ao tentar finalizar a criação da mesma. Impossibilitando os testes de exibição com a vaga criada. 

Como já temos muitas vagas criadas, gostaria de testar a exibição da empresa em uma vaga nova, para validar se suas informações estão sendo vinculadas na tela  "Feed de vagas" 

Evidência no link. 


https://jam.dev/c/a2c70ad3-4692-43a2-87eb-5390f0ab043d

@Jhonny-Freitas @caiquefonseca

**Comment by FernandoMiguelS** [comment]
US da criação de vagas:  https://github.com/SouJunior/products/issues/3#issue-1496870699

@jhonatancostaamaral  

@thiagosansi

**Comment by limaricardo** [comment]
Só pra deixar registrado pro pessoal do Front ou Back que for pegar pra resolver  a task. 

![image](https://github.com/SouJunior/vagas-frontend/assets/81928006/17fd419b-21b7-4cf1-81fc-3439f226e8a5)

Erro 400, com bad request nesses pontos.
