### ISSUE TITLE
[Candidato / Candidatura] - Responsividade feed e matchs de vagas

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#200]
US Relacionada - https://github.com/SouJunior/products/issues/205

### Descrição:
Essa task tem como objetivo implementar a responsividade das páginas de feed de vagas e match de vagas. Essa responsividade visa garantir uma experiência de usuário consistente e de qualidade em diferentes dispositivos e tamanhos de tela.

___

### Subtasks

- [ ] Avaliar e identificar os elementos e componentes das páginas de feed e match de vagas que requerem ajustes para se adaptarem corretamente em dispositivos móveis e outros tamanhos de tela.
- [ ] Aplicar os ajustes necessários para que os elementos sejam redimensionados, reorganizados ou reestilizados adequadamente, garantindo a usabilidade e a legibilidade.
- [ ] Testar as páginas de feed e match de vagas em diferentes dispositivos e tamanhos de tela para verificar se a responsividade está corretamente implementada.
- [ ] Fazer ajustes adicionais, se necessário, para garantir uma experiência de usuário suave e consistente em todas as resoluções de tela.
___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/247098509-0033e00b-f77b-4366-bc8c-800ae50068b0.png)  ![Image](https://user-images.githubusercontent.com/100960828/247098397-4f846652-f6e8-4795-b434-1777c3af2c6f.png)

___

### Critérios de aceitação

- [ ] Os elementos das páginas de feed e match de vagas são ajustados de forma responsiva, de acordo com os diferentes tamanhos de tela.
- [ ] Os elementos são redimensionados, reorganizados ou reestilizados de forma apropriada para garantir a legibilidade e a usabilidade em dispositivos móveis e outros tamanhos de tela.
- [ ] As páginas de feed e match de vagas são testadas em diferentes dispositivos e tamanhos de tela para verificar se a responsividade está corretamente implementada.
- [ ] A responsividade é verificada em diferentes orientações de tela, como retrato e paisagem, garantindo uma experiência consistente em todas as situações.
- [ ] A implementação segue as diretrizes de design responsivo definidas para o aplicativo.

**Comment by caiquefonseca** [comment]
@isabell40liveira, você consegue compartilhar o figma desse projeto com a @BeatrizFFranco ? E-mail dela é bff912@gmail.com

**Comment by caiquefonseca** [comment]
@BeatrizFFranco tentou fazer o cadastro para dar sequencia aos testes e não conseguiu. @FilipeLeoni , você pode ajudar a resolver?

**Comment by FilipeLeoni** [comment]
@BeatrizFFranco O deploy do site está dando problema em algumas rotas, irei falar com o Ricardo para resolvermos. Eu tenho o email e senha tanto de usuário quanto de empresa caso você queria para fazer os teste.

**Comment by BeatrizFFranco** [comment]
Oi @FilipeLeoni , se puderes me enviar um login e senha válidos para testar tanto de empresa, quanto de candidato, eu agradeço. Se você quiser pode enviar para o meu e-mail bff912@gmail.com

**Comment by FilipeLeoni** [comment]
@BeatrizFFranco estamos consertando o deploy para  as rotas funcionar corretamente, enquanto isso não for resolvido não será possivel realizar os teste. Te avisarei assim que estiver pronto.

**Comment by BeatrizFFranco** [comment]
Oi @FilipeLeoni 

Abri o figma e verifiquei que lá possui várias telas de usuário logado no feed de vagas. Gostaria de saber se essa é a versão final?

![WhatsApp Image 2023-07-13 at 09 14 21](https://github.com/SouJunior/vagas-frontend/assets/62288579/55a561d4-932e-4588-9b76-0d4a84228b06)

**Comment by FilipeLeoni** [comment]
Olá @BeatrizFFranco! O Deploy já está funcionando normalmente!

Sobre as telas do figma, o header será alterado na versão final.

**Comment by FernandoMiguelS** [comment]
Boa noite, poderiam me passar o link da versão final? Pois estou com a seguinte situação.  

O teste já foi realizado pela Beatriz, e os problemas apresentados por ela na  Task: Responsividade da Home #207 ainda permanecem no link:  https://vagas-front-end.netlify.app/jobs



![Image](https://github.com/SouJunior/vagas-frontend/assets/134456312/e6409927-ecc9-4a0f-b2fe-0a887187abf7)



Nessa task o mooncoded sinalizou que já realizou o ajuste e está esperando o PR ser aprovado, e nesse já temos a resolução de alguns problemas, e alguns pontos a serem sinalizados. 

Ele informou o seguinte deploy:  https://deploy-preview-226--vagas-front-end.netlify.app/jobs


Preciso que me informem quando a versão atualizada estiver no link oficial para podermos reavaliar corretamente.

**Comment by FernandoMiguelS** [comment]
Boa noite, realizei os testes e identifiquei alguns pontos a serem corrigidos. 



[Evidencia Task 200 .pdf](https://github.com/SouJunior/vagas-frontend/files/12245078/Evidencia.Task.200.pdf)
