### ISSUE TITLE
[Candidato / Candidatura] - Candidatura do usuário

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#201]
US Relacionada - https://github.com/SouJunior/products/issues/205

### Descrição

Essa task tem como objetivo permitir que o usuário selecione o currículo que deseja enviar para uma vaga específica. O usuário terá a opção de clicar em "Me candidatar" caso tenha selecionado um curriculo ou poderá "Cancelar" a candidatura. Se o usuário optar por se candidatar, o currículo será enviado para a API, e um modal de confirmação será exibido, informando que a candidatura foi realizada com sucesso. Além disso, um email deverá ser enviado ao usuário, notificando-o sobre a candidatura bem-sucedida na vaga X. Se o usuário escolher cancelar, um dialog será exibido para confirmar se ele deseja realmente cancelar a candidatura. Se confirmado, o usuário será redirecionado para o feed de vagas.

___

### Subtasks

- [ ] Exibir opções "Me candidatar" e "Cancelar".
- [ ] Ao clicar em "Me candidatar", enviar o currículo para a API.
- [ ] Exibir um modal de confirmação informando que a candidatura foi realizada com sucesso.
- [ ] Enviar um email ao usuário notificando-o sobre a candidatura bem-sucedida na vaga.
- [ ] Ao clicar em "Cancelar", exibir um dialog de confirmação para confirmar a ação do usuário.
- [ ] Redirecionar o usuário para o feed de vagas após confirmar o cancelamento.

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/247100823-d7a0915e-8c66-4a74-8396-d234cde394e6.png)

![Image](https://user-images.githubusercontent.com/100960828/247100860-47649ebc-74cd-4916-a72d-1a8f1510cfd9.png)

![Image](https://user-images.githubusercontent.com/100960828/247100974-65cfe1da-f1f3-4487-bb4a-555445d6bbe6.png)

![Image](https://user-images.githubusercontent.com/100960828/247100912-94f6e44b-a824-47f5-8b2d-558d5f5770fd.png)

___

### Critérios de aceitação

- [ ] O usuário pode selecionar o currículo desejado para candidatura.
- [ ] As opções "Me candidatar" e "Cancelar" são exibidas.
- [ ] Ao clicar em "Me candidatar", o currículo é enviado com sucesso para a API.
- [ ] Um modal de confirmação é exibido, informando que a candidatura foi realizada com sucesso.
- [ ] Um email é enviado ao usuário, notificando-o sobre a candidatura bem-sucedida na vaga.
- [ ] Ao clicar em "Cancelar", um dialog de confirmação é exibido para confirmar a ação do usuário.
- [ ] Após confirmar o cancelamento, o usuário é redirecionado para o feed de vagas.
- [ ] A funcionalidade é testada em diferentes cenários, garantindo que a candidatura, confirmação e cancelamento funcionem corretamente.
- [ ] A implementação segue as diretrizes de design e padrões definidos para o aplicativo.
