### ISSUE TITLE
[Empresa] - Visualizar candidaturas

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#215]
US Relacionada - [#230](https://github.com/SouJunior/products/issues/230)

### Descrição:
Essa task tem o objetivo de implementar a funcionalidade de visualizar as candidaturas de uma determinada vaga publicada pela empresa logada. Podendo visualizar o nome e curriculo dos candidatos.

___

### Subtasks

- [ ] Exibir as vagas publicadas pela empresa logada
- [ ] Exibir Card com informações dos candidatos
- [ ] Aplicar transparencia de 60% nas vagas não selecionadas
- [ ] Filtro de vagas ativas ou finalizadas

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/252327925-ae4fd1a9-024e-4f85-a97d-e192396b57d3.png)

___

### Critérios de Aceitação

- [ ] A empresa deve poder visualizar as vagas publicadas;
- [ ] A empresa deverá poder filtrar por vagas ativas ou vagas encerradas;
- [ ] A empresa deverá poder visualizar os candidatos de uma determinada vaga;

**Comment by mooncoded** [comment]
@wandersonDeve Você poderia dar uma olhada na rota de puxar os candidatos do backend, estou precisando dela para finalizar essa task, acredito que seja a rota /applications

**Comment by wandersonDeve** [comment]
/job/:id @mooncoded

**Comment by AlineBoechat** [comment]
@barbaraluzz pode me passar um Feedback sobre essa US? Pergunto pois entendemos a visualização dos candidatos pela empresa a partir da área de candidaturas recebidas na gestão de acompanhamento.
