### ISSUE TITLE
[Empresa] - Visualizar Vagas Postadas

### ISSUE THREAD

**Issue by mooncoded** [SouJunior/vagas-frontend#216]
US Relacionada - [#228](https://github.com/SouJunior/products/issues/228)

### Descrição:
Essa task tem o objetivo de implementar a funcionalidade de visualizar as vagas postadas da empresa logada. As informações devem ser representadas em uma lista, com a data que a vaga foi postada e o status de cada vaga para ter controle e evitar duplicidade de vagas postadas pela mesma empresa.

___

### Subtasks

- [ ] Exibir as vagas postadas relacionadas a empresa logada
- [ ] Exibir dropdown com as opções referente ao cancelamento da vaga
- [ ] Botão para edição da vaga
- [ ] Filtro de vagas ativas, todas e encerradas

___

### Protótipo

![Image](https://user-images.githubusercontent.com/121585284/240781514-5eb791b5-973a-4359-b657-a4b29b4a9bcb.png)

___

### Critérios de Aceitação

- [ ] A empresa deve poder visualizar as vagas publicadas referentes a sua empresa;
- [ ] A empresa deverá poder filtrar por vagas ativas ou vagas encerradas;
- [ ] A empresa deverá poder encerrar determinada vaga;
- [ ] A empresa deverá poder editar as vagas;

**Comment by caiquefonseca** [comment]
@mooncoded você está com algum impedimento para prosseguir com essa Tasks?

**Comment by mooncoded** [comment]
@caiquefonseca Sim, discutimos isso na Review, precisamos de uma rota do backend que não estava pronta, vou checar hoje se já foi feita para prosseguir com a task

**Comment by caiquefonseca** [comment]
@wandersonDeve , estamos precisando que o back-end 

- [ ] Filtro de vagas ativas, todas e encerradas
- [ ] Rota para finalizar a vaga (rota deletejobs/id)
