### ISSUE TITLE
[Empresa] - Visualizar Curriculo e vaga (Layout)

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#227]
US Relacionada - [#231](https://github.com/SouJunior/products/issues/231)

### Descrição:
Essa taks tem como objetivo a empresa visualizar a página match de vagas, contendo o curriculo selecionado e vaga selecionada, com a opção de baixar o curriculo.

___

### Subtasks

- [ ] Visualizar curriculo selecionado
- [ ] Visualizar vaga selecionada
- [ ] Botão para baixar o curriculo
- [ ] Responsividade

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/255949770-de171d11-03a4-417a-8a0d-eb6eeec89a68.png)

___

**Comment by caiquefonseca** [comment]
@FilipeLeoni , essa task não deveria ter os critérios de aceitação, assim como a outra?

**Comment by caiquefonseca** [comment]
> @caiquefonseca Atualizado!

Obrigado 😊

**Comment by AlineBoechat** [comment]
@barbaraluzz o currículo é cadastrado na Cereal, mas o acesso da empresa ao currículo é feito a partir do acompanhamento da candidatura. Pode me passar um Feedback sobre essa US? Podemos colocar na coluna de exclusão?

**Comment by barbaraluzz** [comment]
> [@barbaraluzz](https://github.com/barbaraluzz) o currículo é cadastrado na Cereal, mas o acesso da empresa ao currículo é feito a partir do acompanhamento da candidatura. Pode me passar um Feedback sobre essa US? Podemos colocar na coluna de exclusão?

Olá Aline, penso que essa parte não é da Cereal, acredito ser da Akamaru, nós cuidamos da parte não logada (candidato/empresa), página de cadastro da empresa e vagas até o momento da publicação, ok?
Pelo que vi, todas US que você me mencionou entram na mesma questão, não fazem parte da Cereal.
