### ISSUE TITLE
[Empresa] - Integração com backend (Visualizar curriculo e vaga corretamente)

### ISSUE THREAD

**Issue by FilipeLeoni** [SouJunior/vagas-frontend#228]
US Relacionada - [#]()

### Descrição:
Essa taks tem como objetivo a empresa visualizar a página match de vagas, contendo o curriculo selecionado e vaga selecionada, sendo possivel de baixar o curriculo.

___

### Subtasks

- [ ] Fazer fetch de dados do backend
- [ ] Baixar curriculo 

___

### Protótipo

![Image](https://user-images.githubusercontent.com/100960828/255951495-50df8e6a-60ff-4ed8-a22a-d03557b500f5.png)

___

### Critérios de Aceitação

- [ ] Empresa deverá acessar a página match de vagas ao clicar no icone de curriculo na tela de candidatos.
- [ ] Empresa deverá visualizar o curriculo selecionado da vaga selecionada
- [ ] Empresa poderá visualizar a vaga selecionada
- [ ] Empresa poderá baixar o curriculo.

**Comment by caiquefonseca** [comment]
@mooncoded está Task está ligada a qual US?

**Comment by caiquefonseca** [comment]
@mooncoded , passando a informação que você deixou na PR para aqui também.

"O download do curriculo está atualmente manual, sendo necessário o usuário clicar no botão de download após abrir o pdf do curriculo do navegador, backend está trabalhando para solucionar essa questão."
