### ISSUE TITLE
[Empresa] - Editar Vaga - Layout

### ISSUE THREAD

**Issue by isabelahyeda** [SouJunior/vagas-frontend#237]
US: SouJunior/products#229

Protótipo: [Figma](https://www.figma.com/file/ckOTqIDiOR1oulZd5qUxVD/Projeto%3A-Aplica%C3%A7%C3%A3o?type=design&node-id=347-851&mode=design&t=Qj4vkbSNgMT6wQ9f-0)

### Subtasks

- [x] Criar formulário 1 etapa;
- [x] Criar formulário 2 etapa;
- [x] Criar formulário 3 etapa.
