### ISSUE TITLE
Correção de Bugs

### ISSUE THREAD

**Issue by denyscarvalho** [SouJunior/vagas-frontend#242]
Correção dos Bugs sinalizados na etapa de "Testing"

TASK:

- [ ] Criar Conta Empresa [https://github.com/SouJunior/vagas-backend/issues/80](url)

- [ ] Criar Conta Candidato [https://github.com/SouJunior/vagas-backend/issues/81](url)

- [ ] Criar Conta - Pop Up Cadastro Concluído [https://github.com/SouJunior/vagas-frontend/issues/134](url)

**Comment by denyscarvalho** [comment]
Criar Conta Candidato [https://github.com/SouJunior/vagas-backend/issues/81](https://github.com/orgs/SouJunior/projects/3/views/url) correºc|ao da task serºa feita na Sprint 16
