### ISSUE TITLE
Correção de Bugs Sprint 16

### ISSUE THREAD

**Issue by denyscarvalho** [SouJunior/vagas-frontend#246]
Correção dos Bugs sinalizados na etapa de "Testing"

TASK:

- [ ] Criar Conta Candidato https://github.com/SouJunior/vagas-backend/issues/80 
- [ ] [Empresa/ Candidato] Esqueci a senha - Form Redefinir Senha https://github.com/SouJunior/vagas-frontend/issues/123 
- [ ] [Empresa] alterar senha layout https://github.com/SouJunior/vagas-frontend/issues/232 
- [ ] [Candidato] Alterar senha layout https://github.com/SouJunior/vagas-frontend/issues/230
